spring:
  datasource:
    default:
      url: "jdbc:mysql://localhost:3306/s_k_sample?characterEncoding=utf8&useSSL=false"
      username: "s_k_user"
      password: "s_k_user"
      driverClassName: com.mysql.cj.jdbc.Driver
    sub:
      url: "jdbc:mysql://localhost:3306/s_k_sample?characterEncoding=utf8&useSSL=false"
      username: "s_k_user_test"
      password: "s_k_user"
      driverClassName: com.mysql.cj.jdbc.Driver
  profiles:
    active: prod # prod/mock
